### ISSUE TITLE
[FEATURE REQUEST] Add description to repo

### ISSUE THREAD

**Issue by darigovresearch** [Bioverse-Labs/forest-map-app#2]
Would be helpful to add a description to the repository to help differentiate it from other repositories in your repository list.

![image](https://user-images.githubusercontent.com/30328618/209567114-bc5c341d-f006-41b4-8780-f909114dbb7a.png)

**Comment by zeucxb** [comment]
Done!

**Comment by darigovresearch** [comment]
Can confirm, thanks for the implementation @zeucxb !
